name: flake8-mypy
on:
  workflow_dispatch:
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Flake8 Lint
        uses: py-actions/flake8@v2
        
  mypy:
    needs: flake8-lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy --install-types .
      - name: Echo
        run: echo ${{ github.sha }} OK
